FROM ubuntu:24.04

RUN apt-get update && apt-get install -y \
    charon-systemd \
    strongswan-swanctl \
    curl \
    net-tools \
    iptables \
    iproute2 \
    iputils-ping \
    nmap \
    tcpdump \
    && rm -rf /var/lib/apt/lists/*

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]